export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const VALIDAR_FORMULARIO_EXITO = 'VALIDAR_FORMULARIO_EXITO';
export const VALIDAR_FORMULARIO_ERROR = 'VALIDAR_FORMULARIO_ERROR';

export const CREAR_PRODUCTO = 'CREAR_PRODUCTO';
export const CREAR_PRODUCTO_EXITO = 'CREAR_PRODUCTO_EXITO';
export const CREAR_PRODUCTO_ERROR = 'CREAR_PRODUCTO_ERROR';

