export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const VALIDAR_FORMULARIO_EXITO = 'VALIDAR_FORMULARIO_EXITO';
export const VALIDAR_FORMULARIO_ERROR = 'VALIDAR_FORMULARIO_ERROR';

export const CREAR_PRODUCTO = 'CREAR_PRODUCTO';
export const CREAR_PRODUCTO_EXITO = 'CREAR_PRODUCTO_EXITO';
export const CREAR_PRODUCTO_ERROR = 'CREAR_PRODUCTO_ERROR';

export const DESCARGA_PRODUCTOS = 'DESCARGA_PRODUCTOS';
export const DESCARGA_PRODUCTOS_EXITO = 'DESCARGA_PRODUCTOS_EXITO';
export const DESCARGA_PRODUCTOS_ERROR = 'DESCARGA_PRODUCTOS_ERROR';

export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO';
export const ELIMINAR_PRODUCTO_EXITO = 'ELIMINAR_PRODUCTO_EXITO';
export const ELIMINAR_PRODUCTO_ERROR = 'ELIMINAR_PRODUCTO_ERROR';

export const OBTENER_PRODUCTO = 'OBTENER_PRODUCTO';
export const OBTENER_PRODUCTO_EXITO = 'OBTENER_PRODUCTO_EXITO';
export const OBTENER_PRODUCTO_ERROR = 'OBTENER_PRODUCTO_ERROR';

export const EDITAR_PRODUCTO = 'EDITAR_PRODUCTO';
export const EDITAR_PRODUCTO_EXITO = 'EDITAR_PRODUCTO_EXITO';
export const EDITAR_PRODUCTO_ERROR = 'EDITAR_PRODUCTO_ERROR';